language: cpp
compiler: gcc
os: linux
dist: xenial
sudo: required

install:
  - sudo apt-get -y update
  - sudo apt-get -y install nano wget curl apt-transport-https git cmake python-all-dev python2.7 libpython2.7-dev swig zlib1g liblzma5 wget apt-transport-https bison bzip2 gcc g++ autoconf
  - sudo apt-get -y install software-properties-common
  - sudo apt-get install -y libftgl-dev libtbb2 libtbb-dev libgl1-mesa-dev libfreetype6-dev mesa-common-dev libffi-dev libfontconfig1-dev
  - sudo apt-get install -y libpcre3-dev libxml2-dev
  - sudo add-apt-repository -y ppa:freecad-community/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y freecad

script:
  - pwd
  - cd nix
  - CFLAGS=-O3 CXXFLAGS=-O3 BUILD_CFG=Release python2.7 build-all.py
  - zip -r /home/travis/build/Blocovin/IfcOpenShell.zip /home/travis/build/Blocovin/IfcOpenShell/

deploy:
  provider: releases
  api_key:
    secure: dnT+2Hr5irPzNIzYVmPHLG0Ig7L0d8BziEuRSrg4LyasQkYIdvTxGKps/QeUfU5Mmyr3h58QhuBA16bUwQaOAfanDC2QCMYNwOY7zcVJfaQFN6SuOc9MYtYzApvJzH0uLN5+1HmssrZ3vZplIjOMmch6yn30CFQ62/euwFItFikIw0g5XNKtVik3qOGEBhaWv/nY1WdrHadOmTrhYyG0ClHGqjcYsHlS4B3JFrSHOcwbOa08PNVt0gDgnoaHmIHWHOoG5r2wKSUFY4IG4EiT/Lb6kEZC1GufP+2Pmz9VrX0vxt7S0W1d+Nv1QUnfIGQSwazqe9605ETeCZtYtCJq4JusvgcPwI4kqC/ZxSLlJJiFGijUIYDMEkjc4CPTxqwfvI0rjcwc/CywjNde6s/zl9k87WycBvUHzppnQoSAdaOjYwM4qRt/ZOuW5rY9F6lwVC9zzUx1swD22OoH5c+e1dCrkSWAb59GSZD4Uste0mEYw7K5Lyr1cWvNhYRRVlS7E4zsv3wDc4haUGQd4SfxzHwBwFCjGv5DuT97IyoLQExGGCybaAJXHskXJ/yo8fZw98LOoDUGc9DJLNX1JOy/cAn6igjNUc2rUl8211YU0fv53vB/fAQRkUzfRJiq//afODHjREv1Ra1zCwcmcnPgK3jMty87HLGytDf5CsHCsj4=
  file: /home/travis/build/Blocovin/IfcOpenShell.zip
  on:
    repo: Blocovin/IfcOpenShell
    branch: CI
